### ISSUE TITLE
Clarification on WaveGAN-M and WaveGAN-B

### ISSUE THREAD

**Issue by Michael-H777** [kobeshegu/ECCV2022_WaveGAN#2]
Hello, 

I have been through your paper and code several times, but is still confused on what is the difference between WaveGAN-M and WaveGAN-B. I understand in the WaveUnpool of lofgan_baseindex.py, there are different aggregation strategies (i.e. sum, sumall, cat5). Is the the main difference between WaveGAN-M and WaveGAN-B? 

Can you clarify how would I initialize a WaveGAN-M using LoFGAN from lofgan_baseindex.py, and how would I initialize a WaveGAN-B using LoFGAN from lofgan_baseindex.py? 

many thanks. 

Sincerely, 
Michael

**Comment by kobeshegu** [comment]
Hi, Michael,
Thanks for your interest. In a nutshell, WaveGAN-M averages the frequency information of images in the same batch, whereas WaveGAN-B uses the corresponding frequency information of the same image for generation. Accordingly, their difference is whether to average the frequency information in [here](https://github.com/kobeshegu/ECCV2022_WaveGAN/blob/8ae91f99addc3700f44fb33de3f215faf14bd8a8/networks/lofgan_baseindex.py#L547).

**Comment by kobeshegu** [comment]
Close issue.
