### ISSUE TITLE
About the testing process

### ISSUE THREAD

**Issue by zy-charon** [kobeshegu/ECCV2022_WaveGAN#3]
Hello, when I execute the "python main_metric.py" command, the following error occurs. May I ask what is the reason for this? The training set is Flowers, and the training process directly runs the command "python train.py".
![image](https://github.com/kobeshegu/ECCV2022_WaveGAN/assets/74723536/67372b53-c392-40f3-92fe-49f7bae18c02)

**Comment by kobeshegu** [comment]
Hi, thanks for your interest.
As we have mentioned in [README](https://github.com/kobeshegu/ECCV2022_WaveGAN/blob/8ae91f99addc3700f44fb33de3f215faf14bd8a8/readme.md?plain=1#L104), you need to comment these code as the dim of frequency components is different with that of the training.
Best,
Mengping.

**Comment by zy-charon** [comment]
> 您好，谢谢您的注意。[正如我们在README](https://github.com/kobeshegu/ECCV2022_WaveGAN/blob/8ae91f99addc3700f44fb33de3f215faf14bd8a8/readme.md?plain=1#L104) 中提到的，您需要注意这些代码，因为频率比例的暗淡与训练的不太一样。 最好的， 孟平。[](https://github.com/kobeshegu/ECCV2022_WaveGAN/blob/8ae91f99addc3700f44fb33de3f215faf14bd8a8/readme.md?plain=1#L104)
Thanks for your reply, I tried commenting these codes as you said, but it didn't work. This error occurs in lofGan.py instead of lofGanbaseindex.py, I think I may be training WaveGAN-M.

**Comment by kobeshegu** [comment]
> 

You may need to check your training config then.

**Comment by zy-charon** [comment]
I didn't modify the training configuration, I just ran "python train.py".
![image](https://github.com/kobeshegu/ECCV2022_WaveGAN/assets/74723536/58c628b6-9d8f-4a22-aaad-20b4cc7848e5)
![image](https://github.com/kobeshegu/ECCV2022_WaveGAN/assets/74723536/1e7f0ff5-4c5a-4763-8c5a-68c0c4dac954)

**Comment by zy-charon** [comment]
> > 
> 
> You may need to check your training config then.

Thanks for your reply, I changed all LH(1,2,3).view(8,3,c, h, w) in lofgan.py to LH(1,2,3).view(-1,3,c, h, w ), the program can run.In addition, I would like to ask, if I want to train WaveGAN-B, which parameter should be modified during training. Should you keep the same number of original images and generated images when calculating the FID, for the dataset Flowers, your original images seem to be 510 and the generated images are 2176.

**Comment by kobeshegu** [comment]
> > > 
> > 
> > 
> > You may need to check your training config then.
> 
> Thanks for your reply, I changed all LH(1,2,3).view(8,3,c, h, w) in lofgan.py to LH(1,2,3).view(-1,3,c, h, w ), the program can run.In addition, I would like to ask, if I want to train WaveGAN-B, which parameter should be modified during training. Should you keep the same number of original images and generated images when calculating the FID, for the dataset Flowers, your original images seem to be 510 and the generated images are 2176.

Hi, the amount of the generated images follows strictly with prior literatures, thus no changes are required for reproducing the results.
As for training the config WaveGAN-B, you can refer to [here](https://github.com/kobeshegu/ECCV2022_WaveGAN/blob/8ae91f99addc3700f44fb33de3f215faf14bd8a8/networks/lofgan_baseindex.py#L532) for the difference. The only difference is whether perform mean operation on the frequency signals.
